name:                monad-torrent
version:             0.1.0.0
github:              "githubuser/monad-torrent"
license:             BSD-3-Clause
author:              "Fadil Smajilbasic and Davor Lucic"
maintainer:          "fadil.smajilbasic@ost.ch and davor.lucic@ost.ch"
copyright:           "2024 Fadil Smajilbasic and Davor Lucic"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            A Bittorent Client wirtten in Haskell
category:            Network

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/monad-torrent#readme>

dependencies:
- base >= 4.7 && < 5
- brick
- vty >= 6.0
- vty-unix
- containers
- aeson
- bytestring
- network
- async
- time
- megaparsec
- parsec
- parser-combinators
- base16-bytestring
- cryptohash-sha1
- http-conduit
- network-simple
- directory
- binary
- random
- directory
- stm
- text

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: app

executables:
  monad-torrent-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monad-torrent